version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    environment:
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: admin123
      WP_ADMIN_EMAIL: admin@example.com
      WP_USER: user
      WP_USER_EMAIL: user@example.com
      WP_USER_PASSWORD: user123
    volumes:
      - web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      inception:

networks:
  inception:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/lelanglo/data/database
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/lelanglo/data/web
      o: bind

