version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    environment:
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    volumes:
      - web:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/lelanglo/data/database
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/lelanglo/data/web
      o: bind

