version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wp-php
      - maria-db
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      inception:
    restart: always

  wp-php:
    build: ./requirements/wordpress
    container_name: wp-php
    depends_on:
      - maria-db
    expose:
      - "9000"
    volumes:
      - web:/var/www/html
    environment:
      WORDPRESS_DB_HOST: maria-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_URL: https://localhost
      WORDPRESS_TITLE: "Mon Site WordPress"
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: admin123
      WP_ADMIN_EMAIL: admin@example.com
      WP_USER: user
      WP_USER_EMAIL: user@example.com
      WP_USER_PASSWORD: user123
    networks:
      inception:
    restart: always

  maria-db:
    build: ./requirements/mariadb
    container_name: maria-db
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      inception:
    restart: always
    
networks:
  inception:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/administrateur/data/database
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/administrateur/data/web
      o: bind
