version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wp-php
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  wp-php:
    build: ./requirements/wordpress
    container_name: wp-php
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:

networks:
  inception:
    driver: bridge

